# permissions for end users to edit kymanginxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kymanginx-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kyma-nginx
    app.kubernetes.io/part-of: kyma-nginx
    app.kubernetes.io/managed-by: kustomize
  name: kymanginx-editor-role
rules:
- apiGroups:
  - operator.kyma-project.io
  resources:
  - kymanginxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.kyma-project.io
  resources:
  - kymanginxes/status
  verbs:
  - get
