apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kyma-redis
    app.kubernetes.io/instance: leader-election-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/part-of: kyma-redis
  name: kyma-redis-leader-election-rolebinding
  namespace: kyma-redis-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kyma-redis-leader-election-role
subjects:
- kind: ServiceAccount
  name: kyma-redis-controller-manager
  namespace: kyma-redis-system
